repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: debug-statements
    - id: requirements-txt-fixer
- repo: local
  hooks:
    - id: isort
      name: Run isort formatter
      entry: isort
      language: system
      types: [ python ]

    - id: black
      name: Run black formatter
      entry: black
      language: system
      types: [python]

    - id: flake8
      name: Run flake8 checks
      entry: flake8
      language: system
      types: [python]

    - id: pylint
      name: Run pylint checks
      entry: pylint
      language: system
      types: [python]

    - id: pytest-cov
      name: Run pytest with coverage
      entry: env PYTHONPATH=./src:./tests python -m pytest --cov --cov-report=html --cov-fail-under=25
      language: system
      pass_filenames: false
      types: [ python ]
