version: '3.8'

services:
  api:
    container_name: ${API_CONTAINER_NAME:-nedlia-api}
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_BUILD_TARGET:-development}
    image: ${DOCKER_REGISTRY:-ghcr.io}/${DOCKER_IMAGE_NAME:-nedlia/user-profile-service}:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - mongodb
      - redis
    deploy:
      resources:
        limits:
          memory: ${API_CONTAINER_MEMORY_LIMIT:-512M}
          cpus: ${API_CONTAINER_CPU_LIMIT:-0.5}
    networks:
      - nedlia-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    container_name: ${MONGODB_CONTAINER_NAME:-nedlia-mongodb}
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-secret}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-nedlia_profiles}
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: ${MONGODB_CONTAINER_MEMORY_LIMIT:-1G}
          cpus: ${MONGODB_CONTAINER_CPU_LIMIT:-1.0}
    networks:
      - nedlia-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    container_name: ${REDIS_CONTAINER_NAME:-nedlia-redis}
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-secret}
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: ${REDIS_CONTAINER_MEMORY_LIMIT:-256M}
          cpus: ${REDIS_CONTAINER_CPU_LIMIT:-0.2}
    networks:
      - nedlia-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
  redis_data:

networks:
  nedlia-network:
    driver: bridge
